### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by tquillin** [tquillin/main#1]
https://github.com/tquillin/main/tree/master/Main

I've tried deploying to heroku but to no avail. I've adjusted gitignore, env, procfile, gemfile and rakefiles. I emailed Heroku over the weekend but haven't heard back from them.

The application works locally but not on Heroku.

Heroku is telling me, in the browser, that the application page can't be found. 

Any help would be appreciated.

**Comment by rapala61** [comment]
I'm looking into this, so far it seems that one of the problems is that you have your application root folder `Main` nested in a `main` folder. Heroku is not liking this nested setup because it doesn't conform to what Heroku recognizes as a standard Rails app.

**Comment by tquillin** [comment]
I was wondering about that because every time I heroku create it creates another directory... same thing happens when I git clone a repo. Both commands leave me with two directories within another directory and never know what to do.

**Comment by rapala61** [comment]
Take a look at https://afternoon-citadel-63653.herokuapp.com/  . I made some changes to your `Procfile` and `config/puma.rb` configs and fixed the nested folders so i was able to deploy to heroku. Ill zip and send to you so you can start from there.

**Comment by rapala61** [comment]
[mainApp.zip](https://github.com/tquillin/main/files/134514/mainApp.zip)
